### ISSUE TITLE
Make contact page useful

### ISSUE THREAD

**Issue by rupl** [rupl/chrisruppel.com#40]
If I want to be independent, I need to make my contact page better. Here are some particularly well-designed contact pages:

* https://sarasoueidan.com/contact/ — "what I do, what I **don't** do"
* http://rachelnabors.com/consulting — selling her main service by highlighting its usefulness

## TODOs

- [x] Availability calendar #50
- [x] Describe the services I want to provide #54 
- [x] List logos of select clients from previous work #55 
- [x] Supply a contact form of some sort. #51

**Comment by rupl** [comment]
Ok this part of the site is much better now.
